### ISSUE TITLE
[GUI] Crash with AttributeError when request 'New Buy Order' 

### ISSUE THREAD

**Issue by lorancecall** [ben-abraham/raven-trader-pro#11]
I first made simple sell order followed by clicking buy order, then the GUI crashed with following error

```
> $ python ./main.py                                                 [±main ●▾]
Loaded 1 swaps from disk
Locking UTXO 7642eeaf8923c8506ea3ed54d9d2fa9e3d46194b699a8d35e87a5fff063cc96d|0
<swap_transaction.SwapTransaction object at 0x115705910>
Traceback (most recent call last):
  File "/Users/shlee419/Projects/BlockChain/raven-trader-pro/main_window.py", line 126, in new_buy_order
    buy_dialog = NewOrderDialog("buy", self.swap_storage, prefill=prefill, parent=self)
  File "/Users/shlee419/Projects/BlockChain/raven-trader-pro/new_order.py", line 60, in __init__
    self.update()
  File "/Users/shlee419/Projects/BlockChain/raven-trader-pro/new_order.py", line 179, in update
    if self.total_price > self.swap_storage.balance:
AttributeError: 'SwapStorage' object has no attribute 'balance'
[1]    5978 abort      python ./main.py
```

**Comment by ben-abraham** [comment]
Fixed since posting.
