### ISSUE TITLE
GUI crash when request Buy Order [MAC]

### ISSUE THREAD

**Issue by lorancecall** [ben-abraham/raven-trader-pro#9]
stderr
```
Traceback (most recent call last):
  File "/Users/shlee419/Projects/BlockChain/raven-trader-pro/main_window.py", line 126, in new_buy_order
    buy_dialog = NewOrderDialog("buy", self.swap_storage, prefill=prefill, parent=self)
  File "/Users/shlee419/Projects/BlockChain/raven-trader-pro/new_order.py", line 60, in __init__
    self.update()
  File "/Users/shlee419/Projects/BlockChain/raven-trader-pro/new_order.py", line 179, in update
    if self.total_price > self.swap_storage.balance:
AttributeError: 'SwapStorage' object has no attribute 'balance'
[1]    98012 abort      python ./main.py
```

**Comment by ben-abraham** [comment]
Give this another try. A lot of order creation code was changed in the bulk order changes.
